---
Name: sectionio
---
SiteTree:
  extensions:
    - SectionIOSiteTreeExtension
File:
  extensions:
    - SectionIOFileExtension
---
Only:
  classexists: 'UserDefinedForm_Controller'
---
UserDefinedForm_Controller:
  extensions:
    - SectionIOFormControllerExtension
