---
Name: sectionio
---

SilverStripe\CMS\Model\SiteTree:
  extensions:
    - Innoweb\SectionIO\Extensions\SectionIOSiteTreeExtension
    
SilverStripe\Assets\File:
  extensions:
    - Innoweb\SectionIO\Extensions\SectionIOFileExtension
